# A workflow to check new / changed maps
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  pull-requests: read

jobs:
  check-new-maps:
    uses: Warzone2100/maps-database/.github/workflows/check_new_maps.yml@main
